[tool.poetry]
name = "hse-case"
version = "0.1.0"
description = ""
authors = ["l4blee <l4blee@yandex.ru>"]
readme = "README.md"
packages = [{include = "hse_case"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
